# ChatGLM SDK Config
chatglm:
  sdk:
    config:
      # 状态；true = 开启、false 关闭
      enable: true
      # 官网地址
      api-host: https://open.bigmodel.cn/
      # 官网申请 https://open.bigmodel.cn/usercenter/apikeys
      api-secret-key: b0c604xxxxxxxxxxxxxxxxxxx.xxxxxxx2iXY
      # 知识星球 Cookie 你需要获取你的 cookie 登录
      cookie: zsxq_access_token=5895F417-4688-C024-A41A-836BBB2238C3_E4719BF902A2D77B; zsxqsessionid=40573ad34cb0517ec8dddb212b28b271
